version: "2"
# TODO: start using gunicorn for api and app
services:
    nginx:
        build: ./nginx
        image: arc/nginx:0.1.0
        restart: always
        ports:
            - "80:80"

    ws_server:
        build: ./ws_server
        image: arc/ws_server:0.1.0
        restart: always
        command: python run.py
        expose:
            - "5555"

    api_server:
        build: ./api_server
        image: arc/api_server:0.1.0
        restart: always
        command: python run.py
        expose:
            - "10000"
        environment:
            # You should pass your JWT_SECRET here
            - JWT_SECRET=${JWT_SECRET}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        depends_on:
            - ws_server
            - postgres

    postgres:
        build: ./postgres
        image: arc/postgre:0.1.0
        restart: always
        environment:
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_USER=${POSTGRES_USER}
        #expose:
        #    - "5432"
        ports:
            - "5432:5432"
