version: "2"
services:
    nginx:
        build: ./nginx
        image: arc/nginx:0.1.0
        restart: always
        ports:
            - "80:80"

    ws_server:
        build: ./ws_server
        image: arc/ws_server:0.1.0
        restart: always
        command: python run.py
        expose:
            - "5555"

    api_server:
        build: ./api_server
        image: arc/api_server:0.1.0
        restart: always
        # TODO: need to start using gunicorn for this
        command: python run.py
        expose:
            - "10000"

    app:
        build: ./app
        image: arc/app:0.1.0
        restart: always
        # TODO: need to start using gunicorn for this
        command: python run.py
        expose:
            - "1000"
        # We are going to use volume mounting for developement.
        # Before deployment, its better to comment it out.
        # volumes:
        #    - /e/PyCharm_Projects/arc/app/src:/app/src
        #    - /e/PyCharm_Projects/arc/app/src/build:/app/src/build
