version: "2"
services:
    nginx:
        # We are going to use volume mounting for developement.
        # Before deployment, its better to comment it out.
        volumes:
            - /e/PyCharm_Projects/arc/nginx/client:/client
            - /e/PyCharm_Projects/arc/nginx/client/build:/client/build
